# Generated by Django 4.2.11 on 2024-10-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("description", models.TextField(default="")),
                (
                    "book_type",
                    models.CharField(
                        choices=[
                            ("HC", "Твёрдый переплёт"),
                            ("PB", "Мягкий переплёт"),
                            ("EB", "Электроная книга"),
                        ],
                        default="PB",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
