# Generated by Django 4.2.11 on 2024-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "книга", "verbose_name_plural": "книги"},
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
