# Generated by Django 4.2.11 on 2024-10-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_category_tag_alter_book_options_book_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books.category",
            ),
        ),
    ]
