# Generated by Django 4.2.11 on 2024-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(blank=True, to="books.tag"),
        ),
    ]
